import React from "react";
import styled from "styled-components";

const DivStyle = styled.div`

    @keyframes ldio-nljhd1u1s9 {
    0 % {transform: rotate(0deg)}
    50% {transform: rotate(180deg)}
    100% {transform: rotate(360deg)}
}
    .ldio-nljhd1u1s9 div {
    position: absolute;
    animation: ldio-nljhd1u1s9 1s linear infinite;
    width: 160px;
    height: 160px;
    top: 20px;
    left: 20px;
    border-radius: 50%;
    box-shadow: 0 4px 0 0 #109ad7;
    transform-origin: 80px 82px;
}
    .loadingio-spinner-eclipse-h0yn56jt9da {    
    margin: auto;
    width: 200px;
    height: 200px;
    display: block;
    overflow: hidden;
    background: rgba(NaN, NaN, NaN, 0);
}
    .ldio-nljhd1u1s9 {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
}
    .ldio-nljhd1u1s9 div {box - sizing: content-box;}
    /* generated by https://loading.io/ */
`

const spinner = () => {

    return (
        <DivStyle>
            <div className="loadingio-spinner-eclipse-h0yn56jt9da">
                <div className="ldio-nljhd1u1s9">
                    <div></div>
                </div>
            </div>
        </DivStyle>
    );
};


export default spinner;